

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@dc2tst-scan.sampath.lk:1523/tcmndb?oracle.jdbc.timezoneAsRegion=false
spring.datasource.username=casv2apn
spring.datasource.password=ENC(egnazb8h9Lolhm67zoKJe0jwnQmolc6U)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

app.allow.sending.email=true

#Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=2000000


# Encryption Data
enc.key=kFOeHvpni5XmL2SO5qHl+Sn9tvKPdFoTrex0e06qCwvMXBmehbRbIw4p8fXU0ClBknsJ/WBaWnF66nHMsEo8I/9EUTon/LwpU34eAz4IH/rs1/MY6L4Bvo50bVx2HIIzejlxui7rw8t/cq2Bb3qGO83m5upcbzyRlwMhTFxhNkJ35SzzpZ4/caegLTfVJbzO5xYjN07ChIfkAKHR2YQWmDwosXVj4hAjdpVYKrOG0d4CElJLoKTRiBttMBgt7PpkO2h9H+QKRJAhklGEltOdWO176sY/q/g27A3o8r2+YTuIGxHQ06vHt7kY6m3UQc6+Ghdl5ja3sYHULez7nq3M/w==
cert.path=C:/usr/SampathBank.p12
cert.password=password

logging.path=logs/
logging.common-name=cas_covenant_LOG
logging.error-name=cas_covenant_ERROR_LOG

apps.print.html.template.path=/usr/weblogic/Middleware/logs/templates/print

apps.covenant.request.uuid = Req_122
covenant.list=http://192.168.130.191:9604/v1.0.0/LoanOps/GetCovenantList/Inq
existing.finacle.covenant=http://192.125.125.114:7902/v1.0.0/LoanOps/getCovenantDet
service.timeout.in.milliseconds.max = 180000

