import { Component, Input, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { LocalStorage } from "ngx-webstorage";
import { AuthService } from "src/app/core/service/authentication/auth.service";
import { SETTINGS } from "src/app/core/setting/commons.settings";
import * as JSEncryptModule from "jsencrypt";
import { Constants } from "src/app/core/setting/constants";
import { ApplicationService } from "src/app/core/service/application/application.service";
import { TokenService } from "src/app/core/service/authentication/token.service";
@Component({
  selector: "app-sso-init",
  templateUrl: "./sso-init.component.html",
  styleUrls: ["./sso-init.component.scss"],
})
export class SsoInitComponent implements OnInit {
  @LocalStorage(SETTINGS.PUBLIC_KEY)
  private readonly publicKey: any;

  @Input("ssoConfig") ssoConfig: any = null;

  constructor(
    private readonly authService: AuthService,
    private readonly activatedRoute: ActivatedRoute,
    private readonly route: Router,
    private readonly applicationService: ApplicationService,
    private readonly tokenService: TokenService
  ) {}

  ngOnInit() {
    if (this.ssoConfig != null) {
      this.handleWithActivatedRoute();
    } else {
      this.authService.getSSOConfigData().then((data: any) => {
        this.ssoConfig = data;
        this.handleWithActivatedRoute();
      });
    }
  }

  handleWithActivatedRoute() {
    this.activatedRoute.queryParams.subscribe((params) => {
      let userAD: string = "";
      if (params["code"]) {
        userAD = this.tokenService.decodeSSOToken(params["code"]);
      }
      this.handleSSO(userAD);
    });
  }

  handleSSO(userAD: any) {
    if (userAD) {
      this.handleUser(userAD);
    } else {
      if (!this.authService.isLoggedIn()) {
        window.open(this.ssoConfig.ssoRedirectUri, "_self");
      } else {
        this.routeToDashboard();
      }
    }
  }

  handleUser(user: any) {
    let userAD: string = user;
    let autoGeneratedPass: string = new Date().getTime().toString();
    const password = this.getEncryptedPassword(autoGeneratedPass);
    this.authService
      .userLogin({
        username: userAD.toLowerCase(),
        password,
      })
      .then((res: any) => {
        if (!res) {
          this.authService.setLoggedOut(this.ssoConfig);
        }
      });
  }

  getEncryptedPassword(password: any) {
    let crypt = new JSEncryptModule.JSEncrypt();
    crypt.setPublicKey(this.publicKey || SETTINGS.KEYS.PUBLIC_KEY);
    password = crypt.encrypt(password);
    return password;
  }

  routeToDashboard() {
    if (
      this.applicationService.getLoggedInUserUPMGroupCode() ==
        Constants.applicationSecurityWorkClass.SDA ||
      this.applicationService.getLoggedInUserUPMGroupCode() ==
        Constants.applicationSecurityWorkClass.SDE
    ) {
      this.route.navigate([SETTINGS.PAGES.committeePaperDashboard]);
    } else {
      this.route.navigate([SETTINGS.PAGES.home]);
    }
  }
}
